# Generated by Django 4.2.5 on 2024-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_book_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
